### ISSUE TITLE
Mod cannot start due to error during version check

### ISSUE THREAD

**Issue by brooswit** [AHilyard/Iceberg#15]
The mod makes a request to https://mc-update-check.anthonyhilyard.com/520110 and currently that is responding with an internal server error (500).

As a result, the server crashes:

```
31.12 00:54:42 [Server] Forge Version Check/INFO [ne.mi.fm.VersionChecker/]: [iceberg] Starting version check at https://mc-update-check.anthonyhilyard.com/520110
31.12 00:54:42 [Server] Forge Version Check/WARN [ne.mi.fm.VersionChecker/]: Failed to process update information
31.12 00:54:42 [Server] INFO com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
31.12 00:54:42 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:975) ~[gson-2.8.9.jar%2320!/:?] {re:mixin}
31.12 00:54:42 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2320!/:?] {re:mixin}
31.12 00:54:42 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2320!/:?] {re:mixin}
31.12 00:54:42 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%2320!/:?] {re:mixin}
31.12 00:54:42 [Server] INFO at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.18.2-40.1.80.jar%23294!/:?] {}
31.12 00:54:42 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:75) [?:?] {re:mixin}
31.12 00:54:42 [Server] INFO at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:114) [fmlcore-1.18.2-40.1.80.jar%23294!/:?] {}
31.12 00:54:42 [Server] INFO Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
31.12 00:54:42 [Server] INFO at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.9.jar%2320!/:?] {}
31.12 00:54:42 [Server] INFO at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.9.jar%2320!/:?] {}
31.12 00:54:42 [Server] INFO at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.9.jar%2320!/:?] {}
31.12 00:54:42 [Server] INFO at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar%2320!/:?] {re:mixin}
31.12 00:54:42 [Server] INFO ... 6 more
```

**Comment by AHilyard** [comment]
Please post your entire latest.log file from the crash.

**Comment by AHilyard** [comment]
Closing this ticket, please reopen if you continue to experience issues.
