### ISSUE TITLE
1.20.1 Crash (Rubidium and Iceberg probably)

### ISSUE THREAD

**Issue by nickodog** [AHilyard/Iceberg#46]
crashes when hovering enchanted items with legendary tooltips mod
[message.txt](https://github.com/AHilyard/Iceberg/files/12404614/message.txt)

**Comment by forkiesassds** [comment]
It is in fact a conflict with Rubidium, as the logs say `java.lang.IllegalArgumentException: The class com.anthonyhilyard.iceberg.renderer.VertexCollector$1 does not implement interface VertexBufferWriter, which is required for compatibility with Sodium`

**Comment by abrossimow** [comment]
Seconding this.
`java.lang.AbstractMethodError: Method com/anthonyhilyard/iceberg/renderer/VertexCollectorSodium$1.isFullWriter()Z is abstract
	at com.anthonyhilyard.iceberg.renderer.VertexCollectorSodium$1.isFullWriter(VertexCollectorSodium.java) ~[Iceberg-1.20.1-forge-1.1.15.jar%23278!/:1.1.15] {re:classloading}
	at net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.tryOf(VertexBufferWriter.java:34) ~[rubidium-mc1.20.1-0.7.1.jar%23305!/:?] {re:mixin,re:classloading}
	at me.jellysquid.mods.sodium.client.render.vertex.VertexConsumerUtils.convertOrLog(VertexConsumerUtils.java:14) ~[rubidium-mc1.20.1-0.7.1.jar%23305!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.entity.ItemRenderer.handler$zff000$renderModelFast(ItemRenderer.java:544) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.render.model.item.ItemRendererMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemRendererMixin,pl:mixin:APP:fabrication.mixins.json:i_woina.blinking_drops.MixinItemRenderer,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinItemRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115189_(ItemRenderer.java) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.render.model.item.ItemRendererMixin,pl:mixin:APP:forbidden_arcanus.mixins.json:ItemRendererMixin,pl:mixin:APP:fabrication.mixins.json:i_woina.blinking_drops.MixinItemRenderer,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinItemRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderBakedModel(CustomItemRenderer.java:464) ~[Iceberg-1.20.1-forge-1.1.15.jar%23278!/:1.1.15] {re:classloading}
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:305) ~[Iceberg-1.20.1-forge-1.1.15.jar%23278!/:1.1.15] {re:classloading}
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:609) ~[Iceberg-1.20.1-forge-1.1.15.jar%23278!/:1.1.15] {re:classloading}
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:348) ~[Iceberg-1.20.1-forge-1.1.15.jar%23278!/:1.1.15] {re:classloading}
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:148) ~[Iceberg-1.20.1-forge-1.1.15.jar%23278!/:1.1.15] {re:classloading}
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:625) ~[Iceberg-1.20.1-forge-1.1.15.jar%23278!/:1.1.15] {re:classloading}
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.m_183452_(ItemModelComponent.java:121) ~[LegendaryTooltips-1.20.1-forge-1.4.5.jar%23288!/:1.4.5] {re:classloading}
	at net.minecraft.client.gui.GuiGraphics.m_280497_(GuiGraphics.java:629) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280677_(GuiGraphics.java:562) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.renderTooltip(GuiGraphics.java:556) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280072_(AbstractContainerScreen.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.ContainerScreen.m_88315_(ContainerScreen.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:fabrication.mixins.json:i_woina.old_background_shade.MixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427) ~[forge-1.20.1-47.2.1-universal.jar%23331!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420) ~[forge-1.20.1-47.2.1-universal.jar%23331!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:fabrication.mixins.json:a_fixes.no_night_vision_flash.MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:globalpacks.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.use_items_while_riding.MixinMinecraftClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:globalpacks.mixins.json:MinecraftMixin,pl:mixin:APP:rubidium.mixins.json:core.MinecraftClientMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.use_items_while_riding.MixinMinecraftClient,pl:mixin:APP:fabrication.mixins.json:a_fixes.uncap_menu_fps.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[client-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar%23104!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar%23104!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar%23104!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%2390!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] `{}``

**Comment by Witherking25** [comment]
bump.
this doesn't look like it would be too hard to fix,
just implement that interface. This not being compatible with rubidium is a little annoying, so i will have to remove for now

**Comment by leafranger** [comment]
I think the error is still present
https://mclo.gs/pGe8B7j

**Comment by AHilyard** [comment]
This issue has been moved to discord: https://discord.gg/UCKjnamDaW
I am much more active there, and it should get more attention there. Thank you for understanding.
