### ISSUE TITLE
Incompatible with Things [Fabric] mod?

### ISSUE THREAD

**Issue by AryonLegacy** [AHilyard/Iceberg#7]
**Describe the bug**
Game crashes on startup, looks like Iceberg uses something the mod also tries to use:

[19:05:19] [main/INFO]: Mixing LivingEntityMixin from iceberg.mixins.json into net.minecraft.class_1309
[19:05:19] [main/ERROR]: Mixin apply for mod things failed things.mixins.json:LivingEntityMixin -> net.minecraft.class_1309: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Variable modifier target for net/minecraft/class_1309::waxGlandWater was removed by another injector [INJECT Applicator Phase -> things.mixins.json:LivingEntityMixin -> Apply Injections ->  -> Inject -> things.mixins.json:LivingEntityMixin->@ModifyVariable::waxGlandWater(F)F from mod things]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Variable modifier target for net/minecraft/class_1309::waxGlandWater was removed by another injector [INJECT Applicator Phase -> things.mixins.json:LivingEntityMixin -> Apply Injections ->  -> Inject -> things.mixins.json:LivingEntityMixin->@ModifyVariable::waxGlandWater(F)F from mod things]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:169) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1374) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:102) [meteor-client-0.4.8-1415.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) [?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) [?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) [Patchouli-1.18-60-FABRIC.jar:?]
	at net.minecraft.class_6396.handler$cmk000$patchouli_addContext(class_6396.java:1016) [client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:57) [client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:32) [client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:153) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
[19:05:19] [main/ERROR]: Minecraft has crashed!

**Comment by AHilyard** [comment]
@AryonLegacy I believe Iceberg is unrelated to this crash, since it does not remove any variables as the error message indicates.  Could you post the full log please?

**Comment by AryonLegacy** [comment]
You might be right, il test later to confirm

**Comment by AHilyard** [comment]
Closing this due to inactivity.  I believe Iceberg is unrelated.
