### ISSUE TITLE
1.21 Crashes on Server starting

### ISSUE THREAD

**Issue by Saereth** [AHilyard/Iceberg#72]
1.21 Neoforge 41.0.146 stable, the mod crashes when loading it on a multiplayer server with the following error:

```
11:20:15  [Error] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
- Iceberg (iceberg) has failed to load correctly
java.lang.IllegalArgumentException: Method public static void com.anthonyhilyard.iceberg.neoforge.server.IcebergNeoForgeServer.event(net.neoforged.neoforge.event.entity.player.PlayerEvent$PlayerLoggedInEvent) has @SubscribeEvent annotation, but takes an argument that is not valid for this busclass net.neoforged.neoforge.event.entity.player.PlayerEvent$PlayerLoggedInEvent
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.ModLoader.waitForFuture(ModLoader.java:281) ~[loader-4.0.21.jar%2360!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.ModLoader.dispatchParallelTask(ModLoader.java:244) ~[loader-4.0.21.jar%2360!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.ModLoader.constructMods(ModLoader.java:152) ~[loader-4.0.21.jar%2360!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:142) ~[loader-4.0.21.jar%2360!/:4.0]
at TRANSFORMER/neoforge@21.0.146/net.neoforged.neoforge.internal.CommonModLoader.begin(CommonModLoader.java:49) ~[neoforge-21.0.146-universal.jar%23348!/:?]
at TRANSFORMER/neoforge@21.0.146/net.neoforged.neoforge.server.loading.ServerModLoader.load(ServerModLoader.java:34) ~[neoforge-21.0.146-universal.jar%23348!/:?]
at TRANSFORMER/minecraft@1.21/net.minecraft.server.Main.main(Main.java:124) ~[server-1.21-20240613.152323-srg.jar%23347!/:?]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.21.jar%2360!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128) ~[loader-4.0.21.jar%2360!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32) ~[loader-4.0.21.jar%2360!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.21.jar%2360!/:4.0]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%2362!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%2362!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%2362!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%2362!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%2362!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%2362!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%2362!/:?]
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
```

**Comment by AHilyard** [comment]
Thank you for the report, this has been resolved in the latest update. :)
