### ISSUE TITLE
[Not fatal bug/error] I encounter this error messages in my log

### ISSUE THREAD

**Issue by Hiusi** [AHilyard/Iceberg#73]
This error does not make my client crash and I don't really know why the error occurred and I decide want to share it incase this is some important bug or something

```
[17:56:46] [Render thread/ERROR]: java.lang.ClassCastException: class com.anthonyhilyard.iceberg.util.EntityCollector$2 cannot be cast to class net.minecraft.class_3222 (com.anthonyhilyard.iceberg.util.EntityCollector$2 and net.minecraft.class_3222 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @51565ec2)
	at tschipp.carryon.events.CommonEvents.lambda$registerEvents$3(CommonEvents.java:66)
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41)
	at net.minecraft.class_1743.handler$gde000$natures_spirit$isValid(class_1743.java:3018)
	at net.minecraft.class_1743.method_7884(class_1743.java)
	at net.minecraft.class_1799.method_7981(class_1799.java:373)
	at com.anthonyhilyard.iceberg.util.EntityCollector.collectEntitiesFromItem(EntityCollector.java:144)
	at com.anthonyhilyard.iceberg.util.EntityCollector.itemCreatesEntity(EntityCollector.java:209)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:348)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:155)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:664)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:121)
	at net.minecraft.class_332.method_51435(class_332.java:713)
	at net.minecraft.class_332.method_51437(class_332.java:651)
	at net.minecraft.class_465.method_2380(class_465.java:182)
	at net.minecraft.class_481.method_25394(class_481.java:790)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$277(class_757.java)
	at net.minecraft.class_757.wrapOperation$dlp000$fabric-screen-api-v1$onRenderScreen(class_757.java:5586)
	at net.minecraft.class_757.mixinextras$bridge$wrapOperation$dlp000$fabric-screen-api-v1$onRenderScreen$278(class_757.java)
	at net.minecraft.class_757.wrapOperation$dph000$fancymenu$wrapRenderScreenFancyMenu(class_757.java:6570)
	at net.minecraft.class_757.mixinextras$bridge$wrapOperation$dph000$fancymenu$wrapRenderScreenFancyMenu$279(class_757.java)
	at net.minecraft.class_757.wrapOperation$fdb000$konkrete$wrapRenderScreen_Konkrete(class_757.java:9102)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by AHilyard** [comment]
This issue has been moved to discord: https://discord.gg/UCKjnamDaW
I am much more active there, and it should get more attention there. Thank you for understanding.
