### ISSUE TITLE
Iceberg crashes when opening the player item menu with latest Sodium [version 0.6.0 (Beta 2)]

### ISSUE THREAD

**Issue by rght925h** [AHilyard/Iceberg#79]
Iceberg [version 1.2.6 Fabric (1.21.x)] crashes when opening the player item menu if Sodium [version 0.6.0 (Beta 2) for Fabric] is loaded. This is on fabric-loader-0.16.5-1.21.1.

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-09-16 18:32:17
Description: Rendering item

java.lang.AbstractMethodError: Receiver class com.anthonyhilyard.iceberg.fabric.services.FabricBufferSourceFactory$2$1 does not define or inherit an implementation of the resolved method 'abstract void push(org.lwjgl.system.MemoryStack, long, int, net.minecraft.class_293)' of interface net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.
	at net.caffeinemc.mods.sodium.client.render.immediate.model.BakedModelEncoder.writeQuadVertices(BakedModelEncoder.java:61)
	at net.minecraft.class_918.renderBakedItemQuads(class_918.java:8095)
	at net.minecraft.class_918.handler$ibf000$sodium$renderModelFast(class_918.java:8073)
	at net.minecraft.class_918.method_23182(class_918.java)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderBakedModel(CustomItemRenderer.java:474)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModelInternal(CustomItemRenderer.java:323)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.getModelBounds(CustomItemRenderer.java:648)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderModel(CustomItemRenderer.java:373)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderGuiModel(CustomItemRenderer.java:155)
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:664)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.method_32666(ItemModelComponent.java:121)
	at net.minecraft.class_332.redirect$hnl000$shulkerboxtooltip$drawPosAwareComponent(class_332.java:7328)
	at net.minecraft.class_332.method_51435(class_332.java:713)
	at net.minecraft.class_332.method_51437(class_332.java:651)
	at net.minecraft.class_465.shulkerboxtooltip$drawMouseoverTooltip(class_465.java:11232)
	at net.minecraft.class_465.shulkerboxtooltip$lockTooltipPosition(class_465.java:10822)
	at net.minecraft.class_465.redirect$hob000$shulkerboxtooltip$lockTooltipPosition(class_465.java:11226)
	at net.minecraft.class_465.method_2380(class_465.java:182)
	at net.minecraft.class_481.method_25394(class_481.java:790)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$280(class_757.java)
	at net.minecraft.class_757.wrapOperation$dkb000$fabric-screen-api-v1$onRenderScreen(class_757.java:5586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by Zelioth** [comment]
This appears to happen on NeoForge 1.21.1 as well. 
[latest.log](https://github.com/user-attachments/files/17064591/latest.log)
[crash-2024-09-19_13.28.20-client.txt](https://github.com/user-attachments/files/17064593/crash-2024-09-19_13.28.20-client.txt)

**Comment by HaXrDEV** [comment]
This also happens with Sodium 5.11 in Fabric 1.21.1 
Crashlog: https://mclo.gs/AQZrElX

**Comment by HaXrDEV** [comment]
Sidenote, it seems that downgrading the mod to 1.2.6 made my particular crash go away.

**Comment by AHilyard** [comment]
This issue has been moved to discord: https://discord.gg/UCKjnamDaW
I am much more active there, and it should get more attention there. Thank you for understanding.
